// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmeGzVisgQ9AgO7ue1GqNxuKom1nPqrbU',
    appId: '1:932879553768:web:be6b63b6c1517de2aba55d',
    messagingSenderId: '932879553768',
    projectId: 'fir-app-35c4c',
    authDomain: 'fir-app-35c4c.firebaseapp.com',
    storageBucket: 'fir-app-35c4c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo51g54we5KsDq_tLUD-JHamdqyRW_ll8',
    appId: '1:932879553768:android:36717c93d7e9f39aaba55d',
    messagingSenderId: '932879553768',
    projectId: 'fir-app-35c4c',
    storageBucket: 'fir-app-35c4c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuqd3qKiC1UomP-hUcWxY2lmpY5W6H3vM',
    appId: '1:932879553768:ios:1c28f7ba04a681c1aba55d',
    messagingSenderId: '932879553768',
    projectId: 'fir-app-35c4c',
    storageBucket: 'fir-app-35c4c.appspot.com',
    iosClientId: '932879553768-alpillhv55m2p2dtsntd6b49o2bai76r.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuqd3qKiC1UomP-hUcWxY2lmpY5W6H3vM',
    appId: '1:932879553768:ios:1c28f7ba04a681c1aba55d',
    messagingSenderId: '932879553768',
    projectId: 'fir-app-35c4c',
    storageBucket: 'fir-app-35c4c.appspot.com',
    iosClientId: '932879553768-alpillhv55m2p2dtsntd6b49o2bai76r.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuth',
  );
}
